#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MEDIACAPTURE_EXTENSIONS__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MEDIACAPTURE_EXTENSIONS__TYPEDEFS_HPP


namespace mediacapture::detail
{
    enum class get_user_media_semantics_t {BROWSER_CHOOSES, USER_CHOOSES};

    // TODO : get-user-media() business
}


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MEDIACAPTURE_EXTENSIONS__TYPEDEFS_HPP
