#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_GAMEPAD__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_GAMEPAD__TYPEDEFS_HPP

namespace gamepad::detail
{
    enum class gamepad_mapping_type_t {EMPTY_, STANDARD, XR_STANDARD};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_GAMEPAD__TYPEDEFS_HPP
