#ifndef SBROWSER2_SRC_JAVASCRIPT_ENVIRONMENT_ISOLATE_DATA_SLOTS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_ENVIRONMENT_ISOLATE_DATA_SLOTS_HPP

namespace javascript::isolate_data_slots
{
    constexpr auto mutation_observers = 0;
}

#endif //SBROWSER2_SRC_JAVASCRIPT_ENVIRONMENT_ISOLATE_DATA_SLOTS_HPP
