#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_ORIENTATION_SENSOR_ORIENTATION_SENSOR_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_ORIENTATION_SENSOR_ORIENTATION_SENSOR_PRIVATE_HPP

#include "ext/pimpl.hpp"
#include "sensors/sensor_private.hpp"


DEFINE_PRIVATE_CLASS(orientation_sensor, orientation_sensor) : sensors::sensor_private {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_ORIENTATION_SENSOR_ORIENTATION_SENSOR_PRIVATE_HPP
