#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_TOUCH_EVENTS__TYPEDEF_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_TOUCH_EVENTS__TYPEDEF_HPP

namespace touch_events::detail
{
    enum class touch_type_t {DIRECT, STYLUS};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_TOUCH_EVENTS__TYPEDEF_HPP
