#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_REMOTE_PLAYBACK_DETAIL_REMOTE_PLAYBACK_INTERNALS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_REMOTE_PLAYBACK_DETAIL_REMOTE_PLAYBACK_INTERNALS_HPP


namespace remote_playback::detail
{
    auto monitor_list_of_available_remote_playback_devices()
            -> void;
};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_REMOTE_PLAYBACK_DETAIL_REMOTE_PLAYBACK_INTERNALS_HPP
