#ifndef SBROWSER2_SRC_JAVASCRIPT_MACROS_FEATURE_SUPPORT_HPP
#define SBROWSER2_SRC_JAVASCRIPT_MACROS_FEATURE_SUPPORT_HPP


#if __has_include(<gl/GL.h>)
    #define __open_gl_supported
#endif


#endif //SBROWSER2_SRC_JAVASCRIPT_MACROS_FEATURE_SUPPORT_HPP
