#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_NAVIGATION_TIMING__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_NAVIGATION_TIMING__TYPEDEFS_HPP


namespace navigation_timing::detail
{
    enum class navigation_timing_type_t {NAVIGATE, RELOAD, BACK_FORWARD, PRERENDER};
}


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_NAVIGATION_TIMING__TYPEDEFS_HPP
