#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DOM_NODES_CDATA_SECTION_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DOM_NODES_CDATA_SECTION_PRIVATE_HPP

#include "ext/pimpl.hpp"


DEFINE_PRIVATE_CLASS(dom::nodes, cdata_section) {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DOM_NODES_CDATA_SECTION_PRIVATE_HPP
