#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DOM_NODES_TEXT_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DOM_NODES_TEXT_PRIVATE_HPP

#include "ext/pimpl.hpp"


DEFINE_PRIVATE_CLASS(dom::nodes, text) {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DOM_NODES_TEXT_PRIVATE_HPP
