#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_HTML_MIXINS_TRANSFERABLE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_HTML_MIXINS_TRANSFERABLE_HPP

#define MAKE_TRANSFERABLE(t) \
    t(const t& other);       \
    auto operator=(const t& other) -> decltype(auto);


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_HTML_MIXINS_TRANSFERABLE_HPP
