#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_FILESYSTEM_FILE_SYSTEM_WRITABLE_FILE_STREAM_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_FILESYSTEM_FILE_SYSTEM_WRITABLE_FILE_STREAM_PRIVATE_HPP

#include "ext/pimpl.hpp"
#include "streams/writable/writable_stream_private.hpp"


DEFINE_PRIVATE_CLASS(filesystem, file_system_writable_file_stream) : streams::writable::writable_stream_private {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_FILESYSTEM_FILE_SYSTEM_WRITABLE_FILE_STREAM_PRIVATE_HPP
