#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_PAYMENT_METHOD_ID__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_PAYMENT_METHOD_ID__TYPEDEFS_HPP




namespace payment::detail
{
    using payment_method_identifier_t = ext::string_view;
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_PAYMENT_METHOD_ID__TYPEDEFS_HPP
