#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MEDIACAPTURE_EXTENSIONS_DETAIL_CHANGE_INTERNALS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MEDIACAPTURE_EXTENSIONS_DETAIL_CHANGE_INTERNALS_HPP


namespace mediacapture::extensions::change_internals
{
    auto change_of_configuration()
            -> void;
};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MEDIACAPTURE_EXTENSIONS_DETAIL_CHANGE_INTERNALS_HPP
