#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_XHR__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_XHR__TYPEDEFS_HPP


namespace xhr::detail
{
    enum xml_http_request_response_type_t {/* [WEBAPPSEC-COWL] */ LABELED_JSON};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_XHR__TYPEDEFS_HPP
