#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CSS_MEDIA_QUERIES__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CSS_MEDIA_QUERIES__TYPEDEFS_HPP


namespace css::detail
{
    struct media_queries_t;
}


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CSS_MEDIA_QUERIES__TYPEDEFS_HPP
