#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MAGNETOMETER_MAGNETOMETER_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MAGNETOMETER_MAGNETOMETER_PRIVATE_HPP

#include "sensors/sensor_private.hpp"
#include "ext/pimpl.hpp"


DEFINE_PRIVATE_CLASS(magnetometer, magnetometer) : sensors::sensor_private {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MAGNETOMETER_MAGNETOMETER_PRIVATE_HPP
