#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_PAGE_VISIBILITY__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_PAGE_VISIBILITY__TYPEDEFS_HPP

namespace page_visibility::detail
{
    enum class visibility_state_t {HIDDEN, VISIBLE};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_PAGE_VISIBILITY__TYPEDEFS_HPP
