#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_ARIA_MIXINS_ARIA_MIXIN_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_ARIA_MIXINS_ARIA_MIXIN_PRIVATE_HPP

#include "dom_object_private.hpp"

#include "ext/pimpl.hpp"


DEFINE_PRIVATE_CLASS(aria::mixins, aria_mixin) : virtual dom_object_private {/* TODO */};

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_ARIA_MIXINS_ARIA_MIXIN_PRIVATE_HPP
