#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_REPORTING_REPORT_BODY_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_REPORTING_REPORT_BODY_PRIVATE_HPP

#include "ext/pimpl.ixx"



DEFINE_PRIVATE_CLASS(reporting, report_body) : virtual dom_object_private {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_REPORTING_REPORT_BODY_PRIVATE_HPP
