#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_REFERRER_POLICY__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_REFERRER_POLICY__TYPEDEFS_HPP


namespace referrer_policy::detail
{
    enum referrer_policy_t {
        NO_POLICY, NO_REFERRER, NO_REFERRER_WHEN_DOWNGRADE, SAME_ORIGIN, ORIGIN, STRUCT_ORIGIN,
        ORIGIN_WHEN_CROSS_ORIGIN, STRICT_ORIGIN_WHEN_ROSS_ORIGIN, UNSAFE_URL};
}


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_REFERRER_POLICY__TYPEDEFS_HPP
