#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_STREAMS_READABLE_ABSTRACT_READABLE_STREAM_READER_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_STREAMS_READABLE_ABSTRACT_READABLE_STREAM_READER_PRIVATE_HPP

#include "ext/pimpl.hpp"
#include "streams/mixins/readable_stream_generic_reader_private.hpp"


DEFINE_PRIVATE_CLASS(streams::readable, abstract_readable_stream_reader) : mixins::readable_stream_generic_reader_private {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_STREAMS_READABLE_ABSTRACT_READABLE_STREAM_READER_PRIVATE_HPP
