#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DEVICE_ORIENTATION__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DEVICE_ORIENTATION__TYPEDEFS_HPP

namespace device_orientation::detail
{
    enum class permission_state_t {GRANTED, DENIED};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DEVICE_ORIENTATION__TYPEDEFS_HPP
