#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_RESOURCE_TIMING__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_RESOURCE_TIMING__TYPEDEFS_HPP


namespace resource_timing::detail
{
    enum class cache_mode_t {_, LOCAL, VALIDATED};
}


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_RESOURCE_TIMING__TYPEDEFS_HPP
