#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DOM_ITERATORS_TREE_WALKER_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DOM_ITERATORS_TREE_WALKER_PRIVATE_HPP

#include "ext/pimpl.hpp"

namespace dom::nodes {class node;}


DEFINE_PRIVATE_CLASS(dom::node_iterators, tree_walker)
{
    nodes::node* current;
};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DOM_ITERATORS_TREE_WALKER_PRIVATE_HPP
