#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_SECURE_CONTEXTS__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_SECURE_CONTEXTS__TYPEDEFS_HPP


namespace secure_contexts::detail
{
    enum class trust_type_t {POTENTIALLY_TRUSTWORTHY, NOT_TRUSTWORTHY};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_SECURE_CONTEXTS__TYPEDEFS_HPP
