#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_BATTERY__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_BATTERY__TYPEDEFS_HPP

namespace battery::detail
{
    struct battery_manager_t;
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_BATTERY__TYPEDEFS_HPP
