#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DEVICE_POSTURE__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DEVICE_POSTURE__TYPEDEFS_HPP

namespace device_posture::detail
{
    enum device_posture_type_t {CONTINUOUS, FOLDED, FOLDED_OVER};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_DEVICE_POSTURE__TYPEDEFS_HPP
