#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MEDIACAPTURE_MAIN_OTHER_OVERCONSTRAINED_ERROR_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MEDIACAPTURE_MAIN_OTHER_OVERCONSTRAINED_ERROR_PRIVATE_HPP

#include "ext/pimpl.hpp"
#include "dom/other/dom_exception.hpp"


DEFINE_PRIVATE_CLASS(mediacapture::main::other, overconstrained_error) : dom::other::dom_exception
{
    ext::string constraint;
};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_MEDIACAPTURE_MAIN_OTHER_OVERCONSTRAINED_ERROR_PRIVATE_HPP
