#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_HTML_MEDIA_CAPTURE__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_HTML_MEDIA_CAPTURE__TYPEDEFS_HPP


namespace html_media_capture
{
    enum class capture_t {USER, ENVIRONMENT};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_HTML_MEDIA_CAPTURE__TYPEDEFS_HPP
