#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_WEBAPPSEC__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_WEBAPPSEC__TYPEDEFS_HPP

namespace webappsec::detail
{
    enum class should_t {ALLOWED, BLOCKED};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_WEBAPPSEC__TYPEDEFS_HPP
