#ifndef SRC_EXT_MACROS_EXTENDED_ATTRIBUTES_HPP
#define SRC_EXT_MACROS_EXTENDED_ATTRIBUTES_HPP


#define _EXT_NODISCARD [[nodiscard]]
#define _EXT_FALLTHOUGH [[fallthrough]]


#endif //SRC_EXT_MACROS_EXTENDED_ATTRIBUTES_HPP
