#ifndef SBROWSER2_SRC_EXT_MACROS_EXTENDED_ATTRIBUTES_HPP
#define SBROWSER2_SRC_EXT_MACROS_EXTENDED_ATTRIBUTES_HPP


#define _EXT_NODISCARD [[nodiscard]]
#define _EXT_FALLTHOUGH [[fallthrough]]


#endif //SBROWSER2_SRC_EXT_MACROS_EXTENDED_ATTRIBUTES_HPP
