#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_GEOLOCATION_GEOLOCATION_POSITION_ERROR_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_GEOLOCATION_GEOLOCATION_POSITION_ERROR_PRIVATE_HPP

#include "ext/pimpl.hpp"
#include "dom/other/dom_exception_private.hpp"


DEFINE_PRIVATE_CLASS(geolocation, geolocation_position_error) : dom::other::dom_exception_private {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_GEOLOCATION_GEOLOCATION_POSITION_ERROR_PRIVATE_HPP
