#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_VIRTUAL_KEYBOARD__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_VIRTUAL_KEYBOARD__TYPEDEFS_HPP

namespace virtual_keyboard::detail
{
    enum class policy_t {AUTO, MANUAL, _};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_VIRTUAL_KEYBOARD__TYPEDEFS_HPP
