#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_ACCELEROMETER_ACCELEROMETER_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_ACCELEROMETER_ACCELEROMETER_PRIVATE_HPP

#include "ext/pimpl.hpp"
#include "sensors/sensor_private.hpp"


DEFINE_PRIVATE_CLASS(accelerometer, accelerometer) : sensors::sensor_private {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_ACCELEROMETER_ACCELEROMETER_PRIVATE_HPP
