#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_RESOURCE_HINTS_DETAIL_RESOURCE_TIMING_INTERNALS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_RESOURCE_HINTS_DETAIL_RESOURCE_TIMING_INTERNALS_HPP


namespace resource_timing::detail
{
    auto initiate_preconnect()
            -> void;
};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_RESOURCE_HINTS_DETAIL_RESOURCE_TIMING_INTERNALS_HPP
