#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CSS_CSSOM__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CSS_CSSOM__TYPEDEFS_HPP


namespace css::detail
{
    struct css_rule_t;
    struct css_style_sheet_t;
}


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CSS_CSSOM__TYPEDEFS_HPP
