#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_PAINT_TIMING_PERFORMANCE_PAINT_TIMING_PRIVATE_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_PAINT_TIMING_PERFORMANCE_PAINT_TIMING_PRIVATE_HPP

#include "ext/pimpl.hpp"
#include "performance_timeline/performance_entry_private.hpp"


DEFINE_PRIVATE_CLASS(paint_timing, performance_paint_timing) : performance_timeline::performance_entry_private {};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_PAINT_TIMING_PERFORMANCE_PAINT_TIMING_PRIVATE_HPP
