#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CLIPBOARD__PIMPL_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CLIPBOARD__PIMPL_HPP

#include "ext/pimpl.hpp"


namespace clipboard::pimpl
{
    DEFINE_PRIVATE_CLASS(clipboard);
    DEFINE_PRIVATE_CLASS(clipboard_item);
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CLIPBOARD__PIMPL_HPP
