#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CSS_BOX_TREE__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CSS_BOX_TREE__TYPEDEFS_HPP

namespace css::detail
{
    enum class fragment_filter_t {DIRECT_FRAGMENTS_ONLY, FRAGMENT_HIERARCHY};
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_CSS_BOX_TREE__TYPEDEFS_HPP
