#pragma once
#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_URL__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_URL__TYPEDEFS_HPP


#include "ext/string.hpp"

namespace url::detail
{
    struct url_t;

    enum class special_scheme_t {FTP, FILE, HTTP, HTTPS, WS, WSS};
    enum class state_override_t {
        SCHEME_START_STATE, SCHEME_STATE, NO_SCHEME_STATE, SPECIAL_RELATIVE_OR_AUTHORITY_STATE, PATH_OR_AUTHORITY_STATE,
        RELATIVE_STATE, RELATIVE_SLASH_STATE, SPECIAL_AUTHORITY_SLASHES_STATE, SPECIAL_AUTHORITY_IGNORE_SLASHES_STATE,
        AUTHORITY_STATE, HOST_STATE, HOSTNAME_STATE, PORT_STATE, FILE_STATE, FILE_SLASH_STATE, FILE_HOST_STATE,
        PATH_START_STATE, PATH_STATE, OPAQUE_PATH_STATE, QUERY_STATE, FRAGMENT_STATE
    };

    using domain_t = ext::string;
};


#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_URL__TYPEDEFS_HPP
