#ifndef SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_WEBSOCKETS__TYPEDEFS_HPP
#define SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_WEBSOCKETS__TYPEDEFS_HPP


namespace websockets::detail
{
    struct websocket_t;
}

#endif //SBROWSER2_SRC_JAVASCRIPT_WEB_APIS_WEBSOCKETS__TYPEDEFS_HPP
